# Project information
site_description: Poojan's website; built using MKDocs
site_author: Poojan Patel
site_url: https://poojandpatel@github.io
site_name: POOJAN PATEL

# Configuration
theme:
  name: material
  language: en
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    primary: #002c56
    accent: indigo
  logo: logo.png
# Navigation Bar
nav:
    - Home: 'index.md'
    - About: 'about.md'

